// <auto-generated />
using System;
using EFRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFRepository.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    [Migration("20260712113030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainCore.Classroom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NumberClassroom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("DomainCore.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DomainCore.GroupSubject", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.HasKey("GroupID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("GroupSubjects");
                });

            modelBuilder.Entity("DomainCore.Lesson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassroomID")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("DateEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DateStart")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfWeer")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ClassroomID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DomainCore.LessonGroup", b =>
                {
                    b.Property<int>("LessonID")
                        .HasColumnType("integer");

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.HasKey("LessonID", "GroupID");

                    b.HasIndex("GroupID");

                    b.ToTable("LessonGroups");
                });

            modelBuilder.Entity("DomainCore.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NameSubjects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DomainCore.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("DomainCore.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherID")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectID")
                        .HasColumnType("integer");

                    b.HasKey("TeacherID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("DomainCore.GroupSubject", b =>
                {
                    b.HasOne("DomainCore.Group", "Group")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainCore.Subject", "Subject")
                        .WithMany("GroupSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DomainCore.Lesson", b =>
                {
                    b.HasOne("DomainCore.Classroom", "Classroom")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassroomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainCore.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainCore.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DomainCore.LessonGroup", b =>
                {
                    b.HasOne("DomainCore.Group", "Group")
                        .WithMany("LessonGroups")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainCore.Lesson", "Lesson")
                        .WithMany("LessonGroups")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DomainCore.TeacherSubject", b =>
                {
                    b.HasOne("DomainCore.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainCore.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DomainCore.Classroom", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DomainCore.Group", b =>
                {
                    b.Navigation("GroupSubjects");

                    b.Navigation("LessonGroups");
                });

            modelBuilder.Entity("DomainCore.Lesson", b =>
                {
                    b.Navigation("LessonGroups");
                });

            modelBuilder.Entity("DomainCore.Subject", b =>
                {
                    b.Navigation("GroupSubjects");

                    b.Navigation("Lessons");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("DomainCore.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
